//
// Created by tao hu on 2020/4/2.
//

#ifndef OPENCVTEST_SIMDCONFIG_H
#define OPENCVTEST_SIMDCONFIG_H

//#define SIMD_SSE_DISABLE

//#define SIMD_SSE2_DISABLE

//#define SIMD_SSE3_DISABLE

//#define SIMD_SSSE3_DISABLE

//#define SIMD_SSE41_DISABLE

//#define SIMD_SSE42_DISABLE

//#define SIMD_AVX_DISABLE

//#define SIMD_AVX2_DISABLE

//#define SIMD_AVX512F_DISABLE

//#define SIMD_AVX512BW_DISABLE

//#define SIMD_VMX_DISABLE

//#define SIMD_VSX_DISABLE

//#define SIMD_NEON_DISABLE

//#define SIMD_NEON_FP16_DISABLE

//#define SIMD_MSA_DISABLE

//#define SIMD_STATIC

#define SIMD_LOG_ENABLE

#define SIMD_ALLOCATE_ERROR_MESSAGE

#define SIMD_ALLOCATE_ASSERT

#define SIMD_NO_MANS_LAND 64

#define SIMD_NEON_RCP_ITER -1

#define SIMD_NEON_ASM_DISABLE

#define SIMD_NEON_PREFECH_SIZE 384

//#define SIMD_OPENCV_ENABLE

//#define SIMD_PERFORMANCE_STATISTIC

//#define SIMD_RUNTIME_STATISTIC

//#define SIMD_FUTURE_DISABLE

#endif //OPENCVTEST_SIMDCONFIG_H
